# deploy.yml
name: deploy blog to dockerhub
on:
  push:
    branches:
      - hexo
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 发布
      - name: docker build
        run: |
          echo  ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
          docker build -t maya1900/todo:latest .
          docker push maya1900/todo:latest
